<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Diladele.Squid.Tray</RootNamespace>
    <AssemblyName>Diladele.Squid.Tray</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\prepared\diladele\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Resources\SquidIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.9" />
  </ItemGroup>
</Project>