<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Diladele.Squid.Tray</RootNamespace>
    <AssemblyName>Diladele.Squid.Tray</AssemblyName>
	  <!-- Target Windows 10/11 64-bit -->
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <PlatformTarget>x64</PlatformTarget>
	  <!-- Make it a single self-contained EXE -->
	  <PublishSingleFile>true</PublishSingleFile>
	  <SelfContained>false</SelfContained>
	  <!-- Custom output folder -->
	  <OutputPath>..\prepared\diladele\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\squid\diladele\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\prepared\diladele\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Resources\SquidIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.5" />
  </ItemGroup>
</Project>